/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_geekband_alpha_ndk_perf_FibLib */

#ifndef _Included_com_geekband_alpha_ndk_perf_FibLib
#define _Included_com_geekband_alpha_ndk_perf_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_geekband_alpha_ndk_perf_FibLib
 * Method:    fibN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_geekband_alpha_ndk_perf_FibLib_fibN
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_geekband_alpha_ndk_perf_FibLib
 * Method:    fibNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_geekband_alpha_ndk_perf_FibLib_fibNI
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
